name: Python Tycheck

on:
  workflow_call:
    inputs:
      mypy-path:
        required: true
        type: string
      mypy-options:
        required: false
        type: string
        default: ""

jobs:
  python-typecheck:
    name: python-typecheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras

      - name: Mypy
        run: uv run mypy ${{ inputs.mypy-path }} ${{ inputs.mypy-options }}
